### ISSUE TITLE
Is this app still working for 2019 AFL season?

### ISSUE THREAD

**Issue by hailieinvain** [evanrobertson/FootyCast#2]
Hi,
Used this app frequently for the 2018 season, will this be continued any further? Replays and live appear to be unavailable.
Appreciate the effort you have put in,
Thanks,
Hailieinvain

**Comment by evanrobertson** [comment]
Hey mate,
I have personally moved to using Kayo, but I will take a look at this for you and see what needs to be changed.

**Comment by evanrobertson** [comment]
@hailieinvain This has been fixed. Tested and working for replays and live.

**Comment by evanrobertson** [comment]
@hailieinvain new version can be downloaded at https://github.com/evanrobertson/FootyCast/releases/tag/1.0.4
