### ISSUE TITLE
Username and Password Login

### ISSUE THREAD

**Issue by evanrobertson** [evanrobertson/FootyCast#3]
I have confirmed that copying your existing token out of the AFL app works fine I do not have an account to try for logging in this year. If you find yourself having an issue with the login method then please reply and we can work through the issue.

Alternatively I am considering dropping the username and password method as we don't really need it and it would remove some of the complexity from the app that we don't particularly need. Happy to take suggestions on this one before I make the change.

**Comment by chrislinke** [comment]
Happy to help test - I’ve got a login for 2019, and having issues playing live video (at least the one I tried)..  Replays work great though!

**Comment by evanrobertson** [comment]
@chrislinke thanks for offering your help, could you confirm what happens in these 2 scenarios for me?

1. Copying id (mis-uid) from the AFL app into FootyCast 
    - Live videos work
    - Replays work
2. Username and Password entered into FootyCast settings
    - Live videos work
    - Replays work

Do you have the capacity to do some debugging for me using Xcode?

**Comment by chrislinke** [comment]
@evanrobertson same for both situations:

I can view replays with no issues, however live streams don’t play.  With the live streams, it loads the player okay, but the media itself doesn’t play. 

I’ve only tried it on one stream (Freo/Roos), but as others become available I’ll find out if it’s across all live streams.

I can try to debug with Xcode, although I’m a complete noob so probably can’t do a lot off my own back/without guidance.
